# Generated by Django 4.1.2 on 2022-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_phone', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_department', models.CharField(max_length=255)),
            ],
        ),
    ]
